### ISSUE TITLE
Error when starting sozi-to-pdf

### ISSUE THREAD

**Issue by jeanparpaillon** [senshu/Sozi-export#1]
I have checked out sozi-export and followed instructions on README.md

When starting sozi-to-pdf, I have the following error:
$ sozi-to-pdf 
module.js:340
    throw err;
    ^

Error: Cannot find module './build/Release/shell'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/sozi-export/node_modules/execSync/index.js:30:11)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)

My platform is Debian testing

**Comment by aumouvantsillage** [comment]
sozi-export has been tested with node.js 0.10.
It seems that you are using a more recent version ([reference](https://github.com/mgutz/execSync/issues/38))

I will provide a fix to make it work with node.js >= 0.11

**Comment by aumouvantsillage** [comment]
It should now work with recent versions of node.js.
Please reopen this issue if you still have the same problem.
