### ISSUE TITLE
event.js error

### ISSUE THREAD

**Issue by codyli520** [senshu/Sozi-export#14]
with `sozi-to-pdf -o <filename> sozi.presentation.html` command, it produced the following error after exporting the last frame.

```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn pdfjam ENOENT
    at _errnoException (util.js:1041:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by ananthp** [comment]
I'm getting the same problem. Ubuntu 17.04. sozi-export 17.8.1

**Comment by aumouvantsillage** [comment]
Please do not add comments to a closed issue.

Open a new issue and give details that could help me reproduce the problem: for instance, tell me exactly what you have installed and which commands you typed. Also check the installation instructions and confirm that you have followed them carefully.
