### ISSUE TITLE
fie non-empty string error in process?

### ISSUE THREAD

**Issue by profejuanca** [senshu/Sozi-export#18]
why apper this error? the file name is correct, the path is the same but this is the output...

sozi-to-video -b 2M -H 1080 -W 1920 -f 60 -i -o /media/juanca/CACHE/GOT GameofThrones_desarmado.sozi.html
Converting GameofThrones_desarmado.sozi.html to /media/juanca/CACHE/GOT
child_process.js:383
    throw new TypeError('"file" argument must be a non-empty string');
    ^

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:383:11)
    at exports.spawn (child_process.js:496:38)
    at Object.exports.exec (/usr/local/lib/node_modules/sozi-export/node_modules/phantomjs-prebuilt/lib/phantomjs.js:72:10)
    at Object.exports.convertToVideo (/usr/local/lib/node_modules/sozi-export/lib/index.js:120:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/sozi-export/cli/sozi-to-video.js:35:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by aumouvantsillage** [comment]
> the file name is correct, the path is the same but this is the output...

Yes. In this message, the "file" argument is the path of the video conversion tool, not the path of your file.

This issue seems related to [this conversation on the Sozi community forum](http://sozi.baierouge.fr/community/d/79-sozi-to-pdf-failing-with-file-argument-must-be-of-type-string).
For short, Sozi-export is based on obsolete software that no longer works in recent environments and we need to find an alternative. I have already opened issue #17 about this.

At the moment, I have no immediate solution except [using Sozi-export in a Docker container](https://hub.docker.com/r/escalope/inkscape-sozi).
